// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArw-LBriOaR1CTypNUhqXi13EWK6juQYU',
    appId: '1:767674898221:web:962c1e1da6509d91e5e5a4',
    messagingSenderId: '767674898221',
    projectId: 'seguruni-35ca8',
    authDomain: 'seguruni-35ca8.firebaseapp.com',
    storageBucket: 'seguruni-35ca8.firebasestorage.app',
    measurementId: 'G-SS3J03PXN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRP1AiQeBP_CtEurVgvUTwwEFW28Xdcfk',
    appId: '1:767674898221:android:d3e106b728b84058e5e5a4',
    messagingSenderId: '767674898221',
    projectId: 'seguruni-35ca8',
    storageBucket: 'seguruni-35ca8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr4JgvLiX7b5BoFKxbLE5b4UGRV2Rtnco',
    appId: '1:767674898221:ios:fd086331979e3c00e5e5a4',
    messagingSenderId: '767674898221',
    projectId: 'seguruni-35ca8',
    storageBucket: 'seguruni-35ca8.firebasestorage.app',
    iosBundleId: 'com.example.seguruni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr4JgvLiX7b5BoFKxbLE5b4UGRV2Rtnco',
    appId: '1:767674898221:ios:fd086331979e3c00e5e5a4',
    messagingSenderId: '767674898221',
    projectId: 'seguruni-35ca8',
    storageBucket: 'seguruni-35ca8.firebasestorage.app',
    iosBundleId: 'com.example.seguruni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArw-LBriOaR1CTypNUhqXi13EWK6juQYU',
    appId: '1:767674898221:web:647ebc5ef646e45be5e5a4',
    messagingSenderId: '767674898221',
    projectId: 'seguruni-35ca8',
    authDomain: 'seguruni-35ca8.firebaseapp.com',
    storageBucket: 'seguruni-35ca8.firebasestorage.app',
    measurementId: 'G-GFW0Z44FPF',
  );
}
